### PR TITLE
fix: json with missed fields parsing [ROAD-12]

### LINKED ISSUE #107: An exception thrown after Snyk scan
I run the scan through the plugin and a moment after that an exception thrown was reported.

```
kotlin.UninitializedPropertyAccessException: lateinit property fixedIn has not been initialized
	at io.snyk.plugin.cli.Vulnerability.getFixedIn(Vulnerability.kt:25)
	at io.snyk.plugin.ui.toolwindow.VulnerabilityDescriptionPanel.getMainBodyPanel(VulnerabilityDescriptionPanel.kt:117)
	at io.snyk.plugin.ui.toolwindow.VulnerabilityDescriptionPanel.<init>(VulnerabilityDescriptionPanel.kt:67)
	at io.snyk.plugin.ui.toolwindow.SnykToolWindowPanel.updateDescriptionPanelBySelectedTreeNode(SnykToolWindowPanel.kt:216)
	at io.snyk.plugin.ui.toolwindow.SnykToolWindowPanel.access$updateDescriptionPanelBySelectedTreeNode(SnykToolWindowPanel.kt:56)
	at io.snyk.plugin.ui.toolwindow.SnykToolWindowPanel$1$1.run(SnykToolWindowPanel.kt:97)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Plugin version: 2.1.2

IDEA version:
```
IntelliJ IDEA 2021.1 (Ultimate Edition)
Build #IU-211.6693.111, built on April 6, 2021
Subscription is active until December 3, 2021.
Runtime version: 11.0.10+9-b1341.35 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3
Jenkins Plugin 0.13.11-2020.3
GC: G1 Young Generation, G1 Old Generation
Memory: 5120M
Cores: 16
Registry: debugger.watches.in.variables=false, ide.balloon.shadow.size=0, scala.erase.compiler.process.jdk.once=false
Non-Bundled Plugins: Key Promoter X (2021.1.1), com.vecheslav.darculaDarkerTheme (1.2.0), io.protostuff.protostuff-jetbrains-plugin (0.13.0), io.snyk.snyk-intellij-plugin (2.1.2), lermitage.intellij.extra.icons (1.51.0.201), org.jetbrains.plugins.go-template (211.6693.44), org.toml.lang (0.2.146.3826-211), Jenkins Control Plugin (0.13.11-2020.3), String Manipulation (8.15.203.000.2), com.attachme (1.0.0), org.jetbrains.plugins.hocon (2020.1.0), izhangzhihao.rainbow.brackets (6.17), org.intellij.scala (2021.1.18), zio.intellij.zio-intellij (2021.1.6.0), Pythonid (211.6693.115), org.jetbrains.plugins.go (211.6693.111), org.rust.lang (0.3.146.3826-211)
Kotlin: 211-1.4.32-release-IJ6693.72
```

### PR DESCRIPTION
**Pull request by ArtsiomCh**
Default value for all fields gotten from JSON, with post check for initialization by actual values on get().

PS should fix #107

### CODE REVIEW

File: src/main/kotlin/io/snyk/plugin/cli/Vulnerability.kt [hunk 1]
```diff
@@ -1,44 +1,54 @@
...
+
+    var exploit: String = NOT_ASSIGNED
+        get() = assertParsedAndGet(field, "name", NOT_ASSIGNED)
+
+    var CVSSv3: String = NOT_ASSIGNED
+        get() = assertParsedAndGet(field, "CVSSv3", NOT_ASSIGNED)
+    var cvssScore: String = NOT_ASSIGNED
+        get() = assertParsedAndGet(field, "cvssScore", NOT_ASSIGNED)
+
+    var fixedIn: Array<String> = EMPTY_STRING_ARRAY
```
Comment (aldanchenko) [inline src/main/kotlin/io/snyk/plugin/cli/Vulnerability.kt:42]: @ArtsiomCh sorry for long reply. A little earlier I looked at the code and now meditating about it. I want to mark your interesting solution with get() method 👍. Cool :). 

And I want to clarify for my self two points: 

1. This exception is related only to one fixedIn property or to all properties? 

2. As I understand original exception is thrown in VulnerabilityDescriptionPanel, not on deserialization of json from CLI, right?

Thanks!

Comment (ArtsiomCh) [reply src/main/kotlin/io/snyk/plugin/cli/Vulnerability.kt:42]: @aldanchenko 
1 reported exception is for not initialized fixedIn field. But the problem is wider: any field could be not initialized by parsed json and we should handle it gracefully. Also here another issue could happens when instead of array those fixedIn field will be in json as just primitive type. And this is not hypothetical problem, we've got this before in Snyk Code. Gonna make the fix for that too
2 Exception show up in VulnerabilityDescriptionPanel cause it's the first place fixedIn is used and due to previous use of lateinit it not fail during parsing process where it should do. 
IMHO lateinit and !! in Kotlin should be used only when no other solution is possible, otherwise such no obvious issue happen...

Comment (aldanchenko) [reply src/main/kotlin/io/snyk/plugin/cli/Vulnerability.kt:42]: @ArtsiomCh thanks for this info and clarifications! I just thinking: maybe we could check and interpret data on ui level? I might wrong, but I'm thinking that cli just need return data "as is".

@pavel-snyk maybe you could suggest something?

Comment (ArtsiomCh) [reply src/main/kotlin/io/snyk/plugin/cli/Vulnerability.kt]: Rewrote the code with nullability for those possible missed in json fields

File: src/test/kotlin/io/snyk/plugin/services/SnykCliServiceTest.kt [hunk 2]
```diff
@@ -391,6 +392,60 @@ class SnykCliServiceTest : LightPlatformTestCase() {
...
+    @Test
+    fun testConvertRawCliStringWithLicenseVulnsToCliResult() {
+        val cli = getCli(project)
+
+        val rawMissedFixedInFieldCliString = getResourceAsString("licence-vulnerabilities.json")
+        val cliResult = cli.convertRawCliStringToCliResult(rawMissedFixedInFieldCliString, "")
+        assertTrue(cliResult.isSuccessful())
+        assertNotNull(cliResult.allCliVulnerabilities?.find { it.vulnerabilities.any { it.fixedIn == null } })
+
+        touchAllFields(cliResult)
```
Comment (pavel-snyk) [inline src/test/kotlin/io/snyk/plugin/services/SnykCliServiceTest.kt:404]: @ArtsiomCh, what the method `touchAllFields` does?

**Review by pavel-snyk — COMMENTED** [review]
It looks how we agreed during the call, only one small comment/question about method in test.

File: src/test/kotlin/io/snyk/plugin/services/SnykCliServiceTest.kt (hunk 2 above)
Comment (ArtsiomCh) [reply src/test/kotlin/io/snyk/plugin/services/SnykCliServiceTest.kt:404]: @pavel-snyk touchAllFields imitate UI reading fields process, i.e. we "touch" all fields to make sure it available and not producing any exception (like late initialization Exception).

Comment (pavel-snyk) [reply src/test/kotlin/io/snyk/plugin/services/SnykCliServiceTest.kt:404]: @ArtsiomCh,
as best practice unit test should test production code and not methods inside test classes, but I see your intention, so would say it's ok in this case.

**Review by pavel-snyk — APPROVED** [review]
