### PR TITLE
fix exceptions when parsing OSS CLI output [ROAD-250]

### LINKED ISSUE #153: NoSuchElementException in Snyk plugin v2.2.1
Hi all,

I am trying to use the Snyk plugin with my SSO credentials within my company. Here are my settings:

Intellij settings

Authentication via button does not work, so I am using the token.

And when I go to the Snyk tab, it is enabled (which means, it does not ask me for authentication anymore). Then I once hit "Run scan", I get the following:

Intellij exception

Full stacktrace:
`java.util.NoSuchElementException: Char sequence is empty.
	at kotlin.text.StringsKt___StringsKt.first(_Strings.kt:71)
	at io.snyk.plugin.services.SnykCliService.convertRawCliStringToCliResult(SnykCliService.kt:64)
	at io.snyk.plugin.services.SnykCliService.scan(SnykCliService.kt:47)
	at io.snyk.plugin.services.SnykTaskQueueService$scheduleCliScan$1.run(SnykTaskQueueService.kt:104)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:510)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)`

If there is anything else I can provide you to support your investigation, please let me know. 
Thanks on beforehand!

### PR DESCRIPTION
**Pull request by ArtsiomCh**
fix: empty oss-cli output case;
fix: miss-formed oss-cli JSON output case;
feat: log all notification shown to user.

PS should fix #153

### CODE REVIEW

File: src/integTest/kotlin/snyk/oss/OssServiceTest.kt [hunk 1]
```diff
@@ -172,6 +172,28 @@ class OssServiceTest : LightPlatformTestCase() {
         touchAllFields(cliResult)
     }
 
+    @Test
+    fun testConvertRawCliStringToCliResultWithEmptyRawString() {
+        val cli = getOssService(project)
+
+        val cliResult = cli.convertRawCliStringToCliResult("")
+        assertFalse(cliResult.isSuccessful())
```
Comment (pavel-snyk) [inline src/integTest/kotlin/snyk/oss/OssServiceTest.kt:180]: minor nitpick: we can use hamcrest matchers something like
```
assertThat(cliResult.isSuccessful(), equalTo(false))
```
This would be more readable, wdyt?

**Review by pavel-snyk — APPROVED** [review]
lgtm, minor comments/suggestions.

File: src/integTest/kotlin/snyk/oss/OssServiceTest.kt (hunk 1 above)
Comment (ArtsiomCh) [reply src/integTest/kotlin/snyk/oss/OssServiceTest.kt:180]: mmm, for me looks a bit more "massive", but yeah, "mathematically" more readable.
will stay with `assertFalse` for now.
